<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteSFixed64" Id="{7b2a4de3-db7e-43cb-9133-2e939ff4fe38}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes an sfixed64 value, without a tag, to the stream.
FUNCTION F_WriteSFixed64 : HRESULT
VAR_IN_OUT
    aBuffer : ARRAY [*] OF BYTE;
    stState : ST_WriterInternalState;
END_VAR
VAR_INPUT
    nValue : LINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteSFixed64 := F_WriteRawLittleEndian64(aBuffer, stState, TO_ULINT(nValue));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>