<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_WriteContext" Id="{98915832-2220-427f-b2c9-3fd5a06439ec}" SpecialFunc="None">
    <Declaration><![CDATA[{warning 'TODO: Implement FB_WriteContext'}
FUNCTION_BLOCK PUBLIC FB_WriteContext
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>