<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteSFixed32" Id="{1954aae2-e95c-4dac-8af1-a579da471d1b}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes an sfixed32 value, without a tag, to the stream.
FUNCTION F_WriteSFixed32 : HRESULT
VAR_IN_OUT
    aBuffer : ARRAY [*] OF BYTE;
    stState : ST_WriterInternalState;
END_VAR
VAR_INPUT
    nValue : DINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteSFixed32 := F_WriteRawLittleEndian32(aBuffer, stState, TO_UDINT(nValue));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>