<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteFixed32" Id="{1c0274d5-4789-43a4-9ff5-fd680c0bf1d5}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes a fixed32 field value, without a tag, to the stream.
FUNCTION F_WriteFixed32 : HRESULT
VAR_IN_OUT      
    stCtx : ST_WriteContext;
END_VAR
VAR_INPUT
    nValue : UDINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteFixed32 := F_WriteRawLittleEndian32(stCtx, nValue);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>