<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteFixed64" Id="{51775a41-adec-4d53-a0bc-e99ec47dceec}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes a fixed64 field value, without a tag, to the stream.
FUNCTION F_WriteFixed64 : HRESULT
VAR_INPUT
    stBuffer    : ST_Span;
END_VAR
VAR_IN_OUT
    stState     : ST_WriterInternalState;
END_VAR
VAR_INPUT
    nValue : ULINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteFixed64 := F_WriteRawLittleEndian64(stBuffer, stState, nValue);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>