<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteInt64" Id="{2093fb42-8ff6-47d7-b0f8-46c0d2962114}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes an int64 field value, without a tag, to the stream.
FUNCTION F_WriteInt64 : HRESULT
VAR_INPUT
    stBuffer    : ST_Span;
END_VAR
VAR_IN_OUT
    stState     : ST_WriterInternalState;
END_VAR
VAR_INPUT
    nValue : LINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteInt64 := F_WriteRawVarint64(stBuffer, stState, nValue);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>