<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteRawBytes" Id="{03486a0e-d593-43a1-9f38-f3fba2cd9d73}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes out part of an array of bytes.
FUNCTION F_WriteRawBytes : HRESULT
VAR_INPUT
    stBuffer    : ST_Span;
END_VAR
VAR_IN_OUT
    stState     : ST_WriterInternalState;
END_VAR
VAR_INPUT CONSTANT
    tBytes  : T_AnyBytes;
    nLength : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_WriteRawBytes := S_OK;

F_WriteRawBytes := F_WriteToBuffer(stBuffer, stState, tBytes, nLength);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>