<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteUInt64" Id="{1c0ef302-717f-4938-884e-42b4d492e8ae}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes a uint64 field value, without a tag, to the stream.
FUNCTION F_WriteUInt64 : HRESULT
VAR_IN_OUT      
    stCtx : ST_WriteContext;
END_VAR
VAR_INPUT
    nValue : ULINT;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteUInt64 := F_WriteRawVarint64(stCtx, nValue);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>