<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_WriteRawLittleEndian32" Id="{929b4b9f-e676-4cd7-af70-6e4ed7a9029d}" SpecialFunc="None">
    <Declaration><![CDATA[// Writes a 32-bit little-endian integer.
FUNCTION F_WriteRawLittleEndian32 : HRESULT
VAR_IN_OUT      
    stCtx : ST_WriteContext;
END_VAR
VAR_INPUT CONSTANT
    nValue : UDINT;
END_VAR
VAR CONSTANT
    cLength : UDINT := SIZEOF(nValue);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WriteRawLittleEndian32 := F_WriteToBuffer(stCtx, F_ToAnyType(nValue), cLength);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>