<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_ParseLength" Id="{93c884db-4f4d-492d-b48f-8e5fbd80cd44}" SpecialFunc="None">
    <Declaration><![CDATA[// Reads a length for length-delimited data.
FUNCTION F_ParseLength : HRESULT
VAR_IN_OUT CONSTANT
    aBuffer : ARRAY [*] OF BYTE;   
END_VAR
VAR_IN_OUT
    stState : ST_ParserInternalState;
END_VAR
VAR_OUTPUT
    nLength : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_ParseLength := F_ParseRawVarint32(aBuffer, stState, nLength);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>