<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_ParseRawLittleEndian64" Id="{be6bf815-3ecb-4adf-a4c6-a29e7ee5429d}" SpecialFunc="None">
    <Declaration><![CDATA[// Parses a 64-bit little-endian integer.
FUNCTION F_ParseRawLittleEndian64 : HRESULT
VAR_IN_OUT      
    stCtx : ST_ParseContext;
END_VAR
VAR_OUTPUT
    nValue : ULINT;
END_VAR
VAR CONSTANT
    cLength : UDINT := SIZEOF(nValue);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_ParseRawLittleEndian64 :=  F_ReadFromBuffer(stCtx, F_ToAnyType(nValue), cLength);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>