<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_ParseRawLittleEndian32" Id="{562fac10-4f40-4f06-ac41-d13ff8cdd378}" SpecialFunc="None">
    <Declaration><![CDATA[// Parses a 32-bit little-endian integer.
FUNCTION F_ParseRawLittleEndian32 : HRESULT
VAR_IN_OUT      
    stCtx : ST_ParseContext;
END_VAR
VAR_OUTPUT
    nValue : UDINT;
END_VAR
VAR CONSTANT
    cLength : UDINT := SIZEOF(nValue);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_ParseRawLittleEndian32 := F_ReadFromBuffer(stCtx, F_ToAnyType(nValue), cLength);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>