<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_ComputeInt64Size" Id="{9a01272b-f82b-4a2c-8837-6978f1e189f1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ComputeInt64Size : UDINT
VAR_INPUT
    nValue  : LINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_ComputeInt64Size := F_ComputeRawVarint64Size(TO_ULINT(nValue));]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>