<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="F_ComputeUInt32Size" Id="{b832eb68-37ad-415d-ae22-5a35e88c53e7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_ComputeUInt32Size : UDINT
VAR_INPUT
    nValue  : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_ComputeUInt32Size := F_ComputeRawVarint32Size(nValue);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>